AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Woodle serverless deployment (Lambda container + HTTP API + S3 + CloudFront)

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  LambdaImageUri:
    Type: String
    Description: ECR image URI for woodle lambda container image
  AppDomainName:
    Type: String
    Default: ""
    Description: Optional custom domain for CloudFront (leave empty to use distribution domain)
  AcmCertificateArn:
    Type: String
    Default: ""
    Description: Optional ACM certificate ARN (us-east-1) for CloudFront custom domain
  EmailEnabled:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable email sending from Lambda
  EmailProvider:
    Type: String
    Default: "ses"
    AllowedValues:
      - "ses"
      - "smtp"
    Description: Outbound email provider used by Lambda
  EmailFromAddress:
    Type: String
    Default: ""
    Description: From address used for outbound poll emails
  EmailSubjectPrefix:
    Type: String
    Default: ""
    Description: Optional subject prefix for outbound poll emails
  EmailSmtpHost:
    Type: String
    Default: "smtp.ionos.de"
    Description: SMTP host used when EmailProvider is smtp
  EmailSmtpPort:
    Type: Number
    Default: 587
    Description: SMTP port used when EmailProvider is smtp
  EmailSmtpUsername:
    Type: String
    Default: "woodle@funknstein.de"
    Description: SMTP username used when EmailProvider is smtp
  EmailSmtpPasswordSecretId:
    Type: String
    Default: ""
    Description: Optional Secrets Manager secret id containing JSON field password for SMTP password

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref AppDomainName, ""]]
  HasCertificate: !Not [!Equals [!Ref AcmCertificateArn, ""]]
  UseAliasConfig: !And [!Condition HasCustomDomain, !Condition HasCertificate]
  IsEmailEnabled: !Equals [!Ref EmailEnabled, "true"]
  IsEmailProviderSes: !Equals [!Ref EmailProvider, "ses"]
  HasEmailFromAddress: !Not [!Equals [!Ref EmailFromAddress, ""]]
  HasEmailSmtpPasswordSecretId: !Not [!Equals [!Ref EmailSmtpPasswordSecretId, ""]]
  UseSesEmailPolicy: !And [!Condition IsEmailEnabled, !Condition IsEmailProviderSes, !Condition HasEmailFromAddress]

Resources:
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub woodle-web-${EnvironmentName}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  PollsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub woodle-polls-${EnvironmentName}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  WebBucketOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub woodle-web-oac-${EnvironmentName}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  NoReferrerResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub woodle-no-referrer-${EnvironmentName}
        Comment: Enforce no-referrer on all viewer responses
        SecurityHeadersConfig:
          ReferrerPolicy:
            Override: true
            ReferrerPolicy: no-referrer

  WebDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: poll/new-step1.html
        HttpVersion: http2
        Origins:
          - Id: web-bucket-origin
            DomainName: !GetAtt WebBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref WebBucketOriginAccessControl
          - Id: api-origin
            DomainName: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPSPort: 443
        DefaultCacheBehavior:
          TargetOriginId: web-bucket-origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          ResponseHeadersPolicyId: !Ref NoReferrerResponseHeadersPolicy
        CacheBehaviors:
          - PathPattern: /poll/new
            TargetOriginId: web-bucket-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD, OPTIONS]
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
            ResponseHeadersPolicyId: !Ref NoReferrerResponseHeadersPolicy
          - PathPattern: /poll/new-step1.html
            TargetOriginId: web-bucket-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD, OPTIONS]
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
            ResponseHeadersPolicyId: !Ref NoReferrerResponseHeadersPolicy
          - PathPattern: /poll*
            TargetOriginId: api-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD]
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            ResponseHeadersPolicyId: !Ref NoReferrerResponseHeadersPolicy
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /poll/new-step1.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /poll/new-step1.html
          - ErrorCode: 500
            ResponseCode: 503
            ResponsePagePath: /error-unavailable.html
          - ErrorCode: 502
            ResponseCode: 503
            ResponsePagePath: /error-unavailable.html
          - ErrorCode: 503
            ResponseCode: 503
            ResponsePagePath: /error-unavailable.html
          - ErrorCode: 504
            ResponseCode: 503
            ResponsePagePath: /error-unavailable.html
        PriceClass: PriceClass_100
        Aliases: !If [HasCustomDomain, [!Ref AppDomainName], !Ref "AWS::NoValue"]
        ViewerCertificate: !If
          - UseAliasConfig
          - AcmCertificateArn: !Ref AcmCertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true

  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${WebBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebDistribution}

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: "$default"
      CorsConfiguration:
        AllowOrigins:
          - !If
            - HasCustomDomain
            - !Sub "https://${AppDomainName}"
            - "*"
        AllowHeaders:
          - Content-Type
          - If-Match
          - Authorization
          - X-Requested-With
          - HX-Request
          - HX-Current-URL
          - HX-Target
          - HX-Trigger
          - HX-Trigger-Name
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        ExposeHeaders:
          - ETag
          - Location

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref LambdaImageUri
      Timeout: 30
      MemorySize: 1024
      Architectures:
        - arm64
      Environment:
        Variables:
          WOODLE_PUBLIC_BASE_URL: !If
            - HasCustomDomain
            - !Sub "https://${AppDomainName}"
            - ""
          WOODLE_S3_ENABLED: "true"
          WOODLE_S3_REGION: !Ref AWS::Region
          WOODLE_S3_BUCKET: !Ref PollsBucket
          WOODLE_S3_PATH_STYLE: "false"
          WOODLE_EMAIL_ENABLED: !Ref EmailEnabled
          WOODLE_EMAIL_PROVIDER: !Ref EmailProvider
          WOODLE_EMAIL_FROM: !Ref EmailFromAddress
          WOODLE_EMAIL_SUBJECT_PREFIX: !Ref EmailSubjectPrefix
          WOODLE_EMAIL_SMTP_HOST: !Ref EmailSmtpHost
          WOODLE_EMAIL_SMTP_PORT: !Ref EmailSmtpPort
          WOODLE_EMAIL_SMTP_USERNAME: !Ref EmailSmtpUsername
          WOODLE_EMAIL_SMTP_PASSWORD: !If
            - HasEmailSmtpPasswordSecretId
            - !Sub "{{resolve:secretsmanager:${EmailSmtpPasswordSecretId}:SecretString:password}}"
            - !Ref AWS::NoValue
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: PollBucketAccess
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub ${PollsBucket.Arn}/polls/*
                - !Sub ${PollsBucket.Arn}/drafts/*
            - Sid: PollBucketListAccess
              Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt PollsBucket.Arn
            - !If
              - UseSesEmailPolicy
              - Sid: PollEmailSesSend
                Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: "*"
                Condition:
                  StringEquals:
                    ses:FromAddress: !Ref EmailFromAddress
              - !Ref AWS::NoValue
      Events:
        ProxyAny:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY
        RootAny:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /
            Method: ANY

Outputs:
  ApiBaseUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com
  FrontendCloudFrontUrl:
    Value: !Sub https://${WebDistribution.DomainName}
  PollsBucketName:
    Value: !Ref PollsBucket
  WebBucketName:
    Value: !Ref WebBucket
